"""
Django settings for TuxTripLogger project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from split_settings.tools import optional, include

ENV = os.getenv("ENV")

settings_pipeline = [
    'components/base.py',
    'components/apps.py',
    'components/middleware.py',
    'components/templates.py',
    'components/static.py',
    'components/i18n.py',
    'components/database.py',
    'components/auth.py',    
    optional('components/extras/*.py'),
    optional('components/local_settings.py')
]

include(*settings_pipeline)

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
