# Generated by Django 5.2.1 on 2025-06-13 16:46

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TuxTripLogger", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="county",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.FloatField(blank=True),
        ),
    ]
