# Generated by Django 5.2.1 on 2025-06-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TuxTripLogger",
            "0003_location_address_location_country_location_county_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="fromloc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_location",
                to="TuxTripLogger.location",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="toloc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_location",
                to="TuxTripLogger.location",
            ),
        ),
    ]
