# Generated by Django 5.2.1 on 2025-06-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TuxTripLogger", "0004_alter_location_lat_alter_location_lon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="county",
            new_name="city",
        ),
    ]
